export const homeObjOne={
    id:'about',
    lightBg:false,
    lightText:true,
    lightTextDesc:true,
    topLine:'About us',
    headline:'talk about your travels',
    description:'share to our forum to where you traveled and who you have met and if u recomend that place or not',
    buttonLabel:'Get started',
    imgStart:true,
    img:require('./bloom.png'),
    alt:'money',
    adjustment:false,
    dark:true,
    primary:false,
    show:true,
    darkText:false
}
export const homeObjTwo={
    id:'discover',
    lightBg:true,
    lightText:false,
    lightTextDesc:false,
    topLine:'Just a Click away',
    headline:'How can you get started',
    description:'All u gotta do is click on the button bellow and signup and you can see what other people recommend or what did they not like about some place',
    buttonLabel:'Signup',
    imgStart:false,
    img:require('./signup.png'),
    alt:'money',
    dark:true,
    adjustment:true,
    primary:true,
    darkText:true,
    show:true
}
export const homeObjThree={
    id:'services',
    lightBg:false,
    lightText:true,
    lightTextDesc:false,
    topLine:'Our Services',
    headline:'We wish for you to have the best experience possible travelling',
    description:'So all you gotta do is login and join our family of thousands of travelling crazed people ',
    imgStart:true,
    adjustment:false,
    img:require('./floater.gif'),
    alt:'money',
    dark:true,
    primary:true,
    show:false,
    darkText:false
}
